package crouskiebackoffice.view;

import crouskiebackoffice.controle.AddingController;
import crouskiebackoffice.model.creation.ICreateWithName;

/**
 * Cette classe représente une fenêtre de dialogue pour ajouter un élément à une
 * liste. Elle prend en paramètre un contrôleur d'ajout et une interface
 * {@link ICreateWithName} qui permet de créer un élément à partir d'un nom. La
 * fenêtre est modale et bloquante jusqu'à ce que l'utilisateur appuie sur le
 * bouton de soumission ou d'annulation.
 *
 * @param <T> Le type d'élément à ajouter à la liste
 */
public class AddingDialog<T> extends javax.swing.JDialog {

    /**
     * Indique si le formulaire a été soumis ou non
     */
    private boolean submited = false;
    /**
     * Le contrôleur d'ajout qui gère la liste d'éléments à ajouter
     */
    private AddingController addingController;
    /**
     * L'interface permettant de créer un élément à partir d'un nom
     */
    private ICreateWithName createWithName;

    /**
     * Construit une fenêtre de dialogue avec un contrôleur d'ajout et une
     * interface de création d'élément à partir d'un nom. La fenêtre est modale
     * et bloquante.
     *
     * @param addingController le contrôleur d'ajout
     * @param createWithName l'interface de création d'élément à partir d'un nom
     */
    public AddingDialog(AddingController addingController, ICreateWithName createWithName) {
        super(MainWindow.instance);
        setModal(true);
        this.addingController = addingController;
        initComponents();
    }

    /**
     * Affiche la fenêtre de dialogue et attend que l'utilisateur soumette ou
     * annule le formulaire. Si le formulaire a été soumis, retourne l'élément
     * sélectionné dans la liste. Si le formulaire a été annulé, retourne null.
     *
     * @return l'élément sélectionné dans la liste ou null si le formulaire a
     * été annulé
     */
    public T getResult() {
        setVisible(true);
        if (submited) {
            return (T) comboBoxChooser.getSelectedItem();
        } else {
            return null;
        }
    }

    /**
     * Met à jour le contenu de la liste déroulante (combo box) avec les données
     * du contrôleur d'ajout.
     */
    private void updateComboBoxChooser() {
        comboBoxChooser.setModel(new javax.swing.DefaultComboBoxModel<>(addingController.getData().toArray()));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(32767, 32767));
        jPanel2 = new javax.swing.JPanel();
        comboBoxChooser = new javax.swing.JComboBox<>();
        filler6 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(32767, 32767));
        panelField = new javax.swing.JPanel();
        defaultInputField = new javax.swing.JTextField();
        filler7 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(32767, 32767));
        addingBtn = new javax.swing.JButton();
        filler2 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(32767, 32767));
        jPanel1 = new javax.swing.JPanel();
        filler5 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(32767, 32767));
        submitBtn = new javax.swing.JButton();
        filler3 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(32767, 32767));
        cancelBtn = new javax.swing.JButton();
        filler4 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(32767, 32767));

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Ajoue");
        setAlwaysOnTop(true);
        setMinimumSize(new java.awt.Dimension(400, 300));
        setModal(true);
        getContentPane().setLayout(new javax.swing.BoxLayout(getContentPane(), javax.swing.BoxLayout.Y_AXIS));
        getContentPane().add(filler1);

        jPanel2.setLayout(new javax.swing.BoxLayout(jPanel2, javax.swing.BoxLayout.LINE_AXIS));

        comboBoxChooser.setModel(new javax.swing.DefaultComboBoxModel<>(addingController.getData().toArray()));
        comboBoxChooser.setMaximumSize(new java.awt.Dimension(32767, 40));
        jPanel2.add(comboBoxChooser);
        jPanel2.add(filler6);

        panelField.setLayout(new javax.swing.BoxLayout(panelField, javax.swing.BoxLayout.Y_AXIS));

        defaultInputField.setMaximumSize(new java.awt.Dimension(400, 40));
        defaultInputField.setPreferredSize(new java.awt.Dimension(200, 25));
        panelField.add(defaultInputField);

        jPanel2.add(panelField);
        jPanel2.add(filler7);

        addingBtn.setText("Ajouter");
        addingBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addingBtnActionPerformed(evt);
            }
        });
        jPanel2.add(addingBtn);

        getContentPane().add(jPanel2);
        getContentPane().add(filler2);

        jPanel1.setLayout(new javax.swing.BoxLayout(jPanel1, javax.swing.BoxLayout.LINE_AXIS));
        jPanel1.add(filler5);

        submitBtn.setText("Valider");
        submitBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitBtnActionPerformed(evt);
            }
        });
        jPanel1.add(submitBtn);
        jPanel1.add(filler3);

        cancelBtn.setText("Annuler");
        cancelBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelBtnActionPerformed(evt);
            }
        });
        jPanel1.add(cancelBtn);
        jPanel1.add(filler4);

        getContentPane().add(jPanel1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Gère l'événement de clic sur le bouton d'ajout. Crée une nouvelle valeur
     * en utilisant le texte entré dans le champ de texte et met à jour la liste
     * déroulante si l'ajout a réussi.
     */
    private void addingBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addingBtnActionPerformed
        if (addingController.createValue(defaultInputField.getText())) {
            updateComboBoxChooser();
        }
    }//GEN-LAST:event_addingBtnActionPerformed

    /**
     * Gère l'événement de clic sur le bouton de validation. Ferme la fenêtre de
     * dialogue en indiquant que la soumission a été effectuée.
     */
    private void submitBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitBtnActionPerformed
        submited = true;
        dispose();
    }//GEN-LAST:event_submitBtnActionPerformed

    /**
     * Gère l'événement de clic sur le bouton d'annulation. Ferme la fenêtre de
     * dialogue sans enregistrer la valeur sélectionnée.
     */
    private void cancelBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelBtnActionPerformed
        dispose();
    }//GEN-LAST:event_cancelBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addingBtn;
    private javax.swing.JButton cancelBtn;
    private javax.swing.JComboBox<Object> comboBoxChooser;
    private javax.swing.JTextField defaultInputField;
    private javax.swing.Box.Filler filler1;
    private javax.swing.Box.Filler filler2;
    private javax.swing.Box.Filler filler3;
    private javax.swing.Box.Filler filler4;
    private javax.swing.Box.Filler filler5;
    private javax.swing.Box.Filler filler6;
    private javax.swing.Box.Filler filler7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    protected javax.swing.JPanel panelField;
    private javax.swing.JButton submitBtn;
    // End of variables declaration//GEN-END:variables
}
