package crouskiebackoffice.view;

import crouskiebackoffice.controle.ControllerEditProduct;
import crouskiebackoffice.controle.ErrorHandeler;
import crouskiebackoffice.controle.Navigator;
import crouskiebackoffice.model.CollectionModelComboBox;
import crouskiebackoffice.model.DataProduct;
import crouskiebackoffice.model.Product;
import crouskiebackoffice.model.listmodel.DynamicListColorModel;
import crouskiebackoffice.model.listmodel.DynamicListModel;
import crouskiebackoffice.model.listmodel.DynamicListSizeModel;
import crouskiebackoffice.model.listmodel.DynamicListTagModel;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JCheckBox;
import javax.swing.JComboBox;
import javax.swing.JFormattedTextField;
import javax.swing.JTextArea;
import javax.swing.JTextField;

public class EditProduct extends javax.swing.JPanel {

    private ControllerEditProduct controller;
    private Product product;

    /**
     *
     * @param prod le produit à édité
     */
    public EditProduct(Product prod) {
        System.out.println(prod);
        product = prod;
        this.controller = new ControllerEditProduct(this, prod);

        initComponents();

        listSize = new ListDynamicPanel("Taille", controller.getAddDelListIem());
        row3.add(listSize);

        listColor = new ListDynamicPanel("Couleurs", controller.getAddDelListIem());
        row3.add(listColor);

        listTag = new ListDynamicPanel("Tags", controller.getAddDelListIem());
        row3.add(listTag);

        listTag.setModel(new DynamicListTagModel(product));
        listColor.setModel(new DynamicListColorModel(product));
        listSize.setModel(new DynamicListSizeModel(product));

        enVenteCheckBox.setSelected(product.isEnVente());

        nameInput.setText(prod.getName());
        descriptionInput.setText(prod.getDescription());
        priceInput.setText(prod.getPrice() + "");
    }

    private void clearAll() {
        controller.clearAll();

    }

    public JComboBox<String> getCollectionComboBox() {
        return collectionComboBox;
    }

    public JTextArea getDescriptionInput() {
        return descriptionInput;
    }

    public JTextField getNameInput() {
        return nameInput;
    }

    public JFormattedTextField getPriceInput() {
        return priceInput;
    }

    public ListDynamicPanel getListTag() {
        return listTag;
    }

    public ListDynamicPanel getListColor() {
        return listColor;
    }

    public ListDynamicPanel getListSize() {
        return listSize;
    }

    public JCheckBox getEnVenteCheckBox() {
        return enVenteCheckBox;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        filler2 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(32767, 32767));
        row1 = new javax.swing.JPanel();
        nameLabel = new javax.swing.JLabel();
        nameInput = new javax.swing.JTextField();
        collectionLabel = new javax.swing.JLabel();
        collectionComboBox = new javax.swing.JComboBox<>();
        enVenteCheckBox = new javax.swing.JCheckBox();
        row2 = new javax.swing.JPanel();
        descriptionLabel = new javax.swing.JLabel();
        descriptionScrollArea = new javax.swing.JScrollPane();
        descriptionInput = new javax.swing.JTextArea();
        prixLabel = new javax.swing.JLabel();
        priceInput = new javax.swing.JFormattedTextField();
        row3 = new javax.swing.JPanel();
        row4 = new javax.swing.JPanel();
        submitBtn = new javax.swing.JButton();
        cancelBtn = new javax.swing.JButton();
        filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(32767, 32767));

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        setLayout(new javax.swing.BoxLayout(this, javax.swing.BoxLayout.Y_AXIS));
        add(filler2);

        row1.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 40, 5));

        nameLabel.setText("name");
        row1.add(nameLabel);

        nameInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nameInputActionPerformed(evt);
            }
        });
        row1.add(nameInput);

        collectionLabel.setText("collection");
        row1.add(collectionLabel);

        collectionComboBox.setModel(new CollectionModelComboBox(product));
        row1.add(collectionComboBox);

        enVenteCheckBox.setSelected(true);
        enVenteCheckBox.setText("produit en vente");
        row1.add(enVenteCheckBox);

        add(row1);

        row2.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 40, 5));

        descriptionLabel.setText("description");
        row2.add(descriptionLabel);

        descriptionScrollArea.setMinimumSize(new java.awt.Dimension(200, 40));

        descriptionInput.setColumns(20);
        descriptionInput.setRows(5);
        descriptionInput.setMinimumSize(new java.awt.Dimension(200, 40));
        descriptionScrollArea.setViewportView(descriptionInput);

        row2.add(descriptionScrollArea);

        prixLabel.setText("prix (en €)");
        row2.add(prixLabel);

        priceInput.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0.00"))));
        row2.add(priceInput);

        add(row2);

        row3.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 30, 20));
        add(row3);

        row4.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 100, 5));

        submitBtn.setText("Valider");
        submitBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitBtnActionPerformed(evt);
            }
        });
        row4.add(submitBtn);

        cancelBtn.setText("Annuler");
        cancelBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelBtnActionPerformed(evt);
            }
        });
        row4.add(cancelBtn);

        add(row4);
        add(filler1);
    }// </editor-fold>//GEN-END:initComponents

    private void cancelBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelBtnActionPerformed
        Navigator.getInstance().goBack();
        clearAll();
    }//GEN-LAST:event_cancelBtnActionPerformed

    private void submitBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitBtnActionPerformed
        MainWindow.instance.getStatusbar().showMsg("Envoi des données");
        MainWindow.instance.getStatusbar().setLoading(true);

        boolean succes = false;
        try {
            succes = controller.save(nameInput.getText(), descriptionInput.getText(),
                    priceInput.getText(), enVenteCheckBox.isSelected(), collectionComboBox.getModel(),
                    (DynamicListModel) listColor.getModel(), (DynamicListModel) listSize.getModel(), (DynamicListModel) listTag.getModel());
            if (succes) {
                clearAll();
                Navigator.getInstance().goBack();
                DataProduct.getInstance().notif();
            }

        } catch (NumberFormatException | SQLException ex) {
            Logger.getLogger(EditProduct.class.getName()).log(Level.SEVERE, null, ex);
        }
        MainWindow.instance.getStatusbar().setLoading(false);
        if (succes)
            MainWindow.instance.getStatusbar().showMsg("Données envoyé avec succes", 2000);
        else
            MainWindow.instance.getStatusbar().showMsg("Echec lors de l'envoi des données", 2000);
    }//GEN-LAST:event_submitBtnActionPerformed

    private void nameInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameInputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nameInputActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cancelBtn;
    private javax.swing.JComboBox<String> collectionComboBox;
    private javax.swing.JLabel collectionLabel;
    private javax.swing.JTextArea descriptionInput;
    private javax.swing.JLabel descriptionLabel;
    private javax.swing.JScrollPane descriptionScrollArea;
    private javax.swing.JCheckBox enVenteCheckBox;
    private javax.swing.Box.Filler filler1;
    private javax.swing.Box.Filler filler2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField nameInput;
    private javax.swing.JLabel nameLabel;
    private javax.swing.JFormattedTextField priceInput;
    private javax.swing.JLabel prixLabel;
    private javax.swing.JPanel row1;
    private javax.swing.JPanel row2;
    private javax.swing.JPanel row3;
    private javax.swing.JPanel row4;
    private javax.swing.JButton submitBtn;
    // End of variables declaration//GEN-END:variables
    private ListDynamicPanel listTag;
    private ListDynamicPanel listColor;
    private ListDynamicPanel listSize;

}
