package crouskiebackoffice.view;

import javax.swing.ListModel;
import crouskiebackoffice.controle.AddDelListIem;

/**
 *
 * @author wwwazz
 */
public class ListDynamicPanel extends javax.swing.JPanel {

    private AddDelListIem addDel;

    public ListDynamicPanel(String title, AddDelListIem addDel) {
        initComponents();

        this.addDel = addDel;
        this.title.setText(title);
    }

    public void setModel(ListModel listModel) {
        list.setModel(listModel);
    }

    public ListModel getModel() {
        return list.getModel();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        title = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        list = new javax.swing.JList<>();
        jPanel1 = new javax.swing.JPanel();
        addBtn = new javax.swing.JButton();
        delBtn = new javax.swing.JButton();

        setLayout(new javax.swing.BoxLayout(this, javax.swing.BoxLayout.Y_AXIS));

        title.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        title.setText("Title");
        jPanel2.add(title);
        title.getAccessibleContext().setAccessibleName("titleLabel");

        add(jPanel2);

        list.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        list.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        list.setMaximumSize(new java.awt.Dimension(20, 105));
        list.setMinimumSize(new java.awt.Dimension(20, 105));
        list.setPreferredSize(new java.awt.Dimension(20, 105));
        jScrollPane1.setViewportView(list);

        add(jScrollPane1);

        addBtn.setText("+");
        addBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addBtnActionPerformed(evt);
            }
        });
        jPanel1.add(addBtn);

        delBtn.setText("-");
        delBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                delBtnActionPerformed(evt);
            }
        });
        jPanel1.add(delBtn);

        add(jPanel1);
    }// </editor-fold>//GEN-END:initComponents

    private void addBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addBtnActionPerformed
        addDel.add(list);
    }//GEN-LAST:event_addBtnActionPerformed

    private void delBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_delBtnActionPerformed
        addDel.del(list);
    }//GEN-LAST:event_delBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addBtn;
    private javax.swing.JButton delBtn;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JList<String> list;
    private javax.swing.JLabel title;
    // End of variables declaration//GEN-END:variables
}
