package crouskiebackoffice.view;

import crouskiebackoffice.controle.ErrorHandeler;
import crouskiebackoffice.model.DataProduct;
import crouskiebackoffice.model.Observer;

public class VisualisationPanel extends javax.swing.JPanel implements Observer {

    /**
     * Creates new form VisualisationPanel
     */
    public VisualisationPanel() {
        initComponents();
        ErrorHandeler.getInstance().exec(() -> {
            DataProduct.getInstance().registerObserver(this);
        });

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        productVisualisationTable1 = new crouskiebackoffice.view.ProductVisualisationTable();

        setLayout(new java.awt.BorderLayout());

        jScrollPane2.setViewportView(productVisualisationTable1);

        add(jScrollPane2, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane2;
    private crouskiebackoffice.view.ProductVisualisationTable productVisualisationTable1;
    // End of variables declaration//GEN-END:variables

    public void update() {
        repaint();
    }
}
